export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST' 
export const ORDER_CREATE_SUCCESS='ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL= 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST='ORDER_DETAILS_REQUEST' 
export const ORDER_DETAILS_SUCCESS='ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL= 'ORDER_DETAILS_FAIL'

export const ORDER_MY_REQUEST='ORDER_MY_REQUEST' 
export const ORDER_MY_SUCCESS='ORDER_MY_SUCCESS'
export const ORDER_MY_FAIL= 'ORDER_MY_FAIL'
export const ORDER_MY_RESET= 'ORDER_MY_RESET'